### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

### ISSUE THREAD

**Issue by minilab** [ardcore/atom-html-to-css#5]
[Enter steps to reproduce:]

1. opened html file
2. select html-to-css
3. generate
4. error thrown 

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [html-to-css](https://github.com/ardcore/atom-html-to-css) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

```
At /Users/blair.hendriks/.atom/packages/html-to-css/lib/html-to-css.js:64

TypeError: Cannot read property 'getSelectedText' of undefined
    at Object.generate (/packages/html-to-css/lib/html-to-css.js:64:24)
    at /packages/html-to-css/lib/html-to-css.js:50:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:30.2.0 html-to-css:generate (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-css-clean 2.21.0 
autoclose-html 0.23.0 
css-in-js 0.2.0 
html-to-css 0.2.2 
w3c-validation 0.4.0 
```

**Comment by minilab** [comment]
operator error.....
